
package ru.otus.akn.project.soap.salary.client;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalaryCalculatorProvider", targetNamespace = "http://salary.soap.project.akn.otus.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalaryCalculatorProvider {


    /**
     * 
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaxEmployeesSalary", targetNamespace = "http://salary.soap.project.akn.otus.ru/", className = "ru.otus.akn.project.soap.salary.client.GetMaxEmployeesSalary")
    @ResponseWrapper(localName = "getMaxEmployeesSalaryResponse", targetNamespace = "http://salary.soap.project.akn.otus.ru/", className = "ru.otus.akn.project.soap.salary.client.GetMaxEmployeesSalaryResponse")
    @Action(input = "http://salary.soap.project.akn.otus.ru/SalaryCalculatorProvider/getMaxEmployeesSalaryRequest", output = "http://salary.soap.project.akn.otus.ru/SalaryCalculatorProvider/getMaxEmployeesSalaryResponse")
    public BigDecimal getMaxEmployeesSalary();

    /**
     * 
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateAverageSalary", targetNamespace = "http://salary.soap.project.akn.otus.ru/", className = "ru.otus.akn.project.soap.salary.client.CalculateAverageSalary")
    @ResponseWrapper(localName = "calculateAverageSalaryResponse", targetNamespace = "http://salary.soap.project.akn.otus.ru/", className = "ru.otus.akn.project.soap.salary.client.CalculateAverageSalaryResponse")
    @Action(input = "http://salary.soap.project.akn.otus.ru/SalaryCalculatorProvider/calculateAverageSalaryRequest", output = "http://salary.soap.project.akn.otus.ru/SalaryCalculatorProvider/calculateAverageSalaryResponse")
    public BigDecimal calculateAverageSalary();

}
