
package ru.otus.akn.project.soap.salary.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalaryCalculatorService", targetNamespace = "http://salary.soap.project.akn.otus.ru/", wsdlLocation = "http://localhost:8080/SalaryCalculatorService?wsdl")
public class SalaryCalculatorService
    extends Service
{

    private final static URL SALARYCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALARYCALCULATORSERVICE_EXCEPTION;
    private final static QName SALARYCALCULATORSERVICE_QNAME = new QName("http://salary.soap.project.akn.otus.ru/", "SalaryCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SalaryCalculatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALARYCALCULATORSERVICE_WSDL_LOCATION = url;
        SALARYCALCULATORSERVICE_EXCEPTION = e;
    }

    public SalaryCalculatorService() {
        super(__getWsdlLocation(), SALARYCALCULATORSERVICE_QNAME);
    }

    public SalaryCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALARYCALCULATORSERVICE_QNAME, features);
    }

    public SalaryCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, SALARYCALCULATORSERVICE_QNAME);
    }

    public SalaryCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALARYCALCULATORSERVICE_QNAME, features);
    }

    public SalaryCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalaryCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalaryCalculatorProvider
     */
    @WebEndpoint(name = "SalaryCalculatorProviderPort")
    public SalaryCalculatorProvider getSalaryCalculatorProviderPort() {
        return super.getPort(new QName("http://salary.soap.project.akn.otus.ru/", "SalaryCalculatorProviderPort"), SalaryCalculatorProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalaryCalculatorProvider
     */
    @WebEndpoint(name = "SalaryCalculatorProviderPort")
    public SalaryCalculatorProvider getSalaryCalculatorProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://salary.soap.project.akn.otus.ru/", "SalaryCalculatorProviderPort"), SalaryCalculatorProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALARYCALCULATORSERVICE_EXCEPTION!= null) {
            throw SALARYCALCULATORSERVICE_EXCEPTION;
        }
        return SALARYCALCULATORSERVICE_WSDL_LOCATION;
    }

}
