CREATE SEQUENCE EMPLOYEES_SEQ START WITH 1;

CREATE TABLE EMPLOYEES
  (EMPLOYEE_ID NUMBER (19, 0) NOT NULL,
  POSITION_ID NUMBER (19, 0) NOT NULL,
  DEPARTMENT_ID NUMBER (19, 0) NOT NULL,
  FIRST_NAME VARCHAR2 (255 CHAR) NOT NULL,
  LAST_NAME VARCHAR2 (255 CHAR) NOT NULL,
  EMPLOYMENT_DATE DATE NOT NULL,
  SALARY NUMBER (19, 2) NOT NULL,
  BONUS_PERCENT NUMBER (12, 4) DEFAULT 0 NOT NULL,
  MIDDLE_NAME VARCHAR2 (255 CHAR),
  TELEPHONE_NUMBER VARCHAR2 (255 CHAR),
  EMAIL VARCHAR2 (255 CHAR),
  DISMISSAL_DATE DATE,
  USER_ID NUMBER (19, 0),
  CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY (EMPLOYEE_ID));

CREATE SEQUENCE POSITIONS_SEQ START WITH 1;

CREATE TABLE POSITIONS
  (POSITION_ID NUMBER (19, 0) NOT NULL,
    POSITION_NAME VARCHAR2 (255 CHAR) NOT NULL UNIQUE,
    CONSTRAINT PK_POSITION_ID PRIMARY KEY (POSITION_ID));

CREATE SEQUENCE DEPARTMENTS_SEQ START WITH 1;

CREATE TABLE DEPARTMENTS
  (DEPARTMENT_ID NUMBER (19, 0) NOT NULL,
  DEPARTMENT_NAME VARCHAR2 (255 CHAR) NOT NULL UNIQUE,
  CITY VARCHAR2 (255 CHAR),
  FULL_ADDRESS VARCHAR2 (1000 CHAR),
  CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY (DEPARTMENT_ID));

CREATE SEQUENCE PERMISSIONS_SEQ START WITH 1;

CREATE TABLE PERMISSIONS
  (PERMISSION_ID NUMBER (19, 0) NOT NULL,
  PERMISSION_NAME VARCHAR2 (255 CHAR) NOT NULL,
  PERMISSION_CODE VARCHAR2 (255 CHAR) NOT NULL,
  PERMISSION_DESCRIPTION VARCHAR2 (1000 CHAR) NOT NULL,
  CONSTRAINT PK_PERMISSION_ID PRIMARY KEY (PERMISSION_ID));

CREATE SEQUENCE USERS_SEQ START WITH 1;

CREATE TABLE USERS
  (USER_ID NUMBER (19, 0) NOT NULL,
  PASSWORD_HASH VARCHAR2 (255 CHAR) NOT NULL,
  LOGIN VARCHAR2 (255 CHAR) NOT NULL,
  IS_ACTIVE NUMBER (1, 0) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID));

CREATE SEQUENCE AUDIT_HISTORIES_SEQ START WITH 1;

CREATE TABLE AUDIT_HISTORIES
  (AUDIT_HISTORY_ID NUMBER (19, 0) NOT NULL,
  EXECUTION_DATE DATE NOT NULL,
  AUDIT_OPERATION_ID NUMBER (19, 0) NOT NULL,
  USER_ID NUMBER (19, 0) NOT NULL,
  IS_ERROR NUMBER (1, 0) NOT NULL,
  ERROR_INFO VARCHAR2 (1000 CHAR),
  CONSTRAINT PK_AUDIT_HISTORY_ID PRIMARY KEY (AUDIT_HISTORY_ID));

CREATE SEQUENCE AUDIT_OPERATIONS_SEQ START WITH 1;

CREATE TABLE AUDIT_OPERATIONS
  (AUDIT_OPERATION_ID NUMBER (19, 0) NOT NULL,
  OPERATION_NAME VARCHAR2 (255 CHAR) NOT NULL,
  OPERATION_CODE VARCHAR2 (255 CHAR) NOT NULL,
  OPERATION_DESCRIPTION VARCHAR2 (1000 CHAR) NOT NULL,
  CONSTRAINT PK_AUDIT_OPERATION_ID PRIMARY KEY (AUDIT_OPERATION_ID));

CREATE TABLE POSITION_PERMISSION_XREF
  (POSITION_ID NUMBER (19, 0) NOT NULL,
   PERMISSION_ID NUMBER (19, 0) NOT NULL,
   CONSTRAINT PK_POSITION_PERMISSION PRIMARY KEY (POSITION_ID, PERMISSION_ID));

--FOREIGN KEYS

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEE_POSITION_FK
   FOREIGN KEY (POSITION_ID)
   REFERENCES POSITIONS (POSITION_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEE_DEPARTMENT_FK
   FOREIGN KEY (DEPARTMENT_ID)
   REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEE_USER_FK
   FOREIGN KEY (USER_ID)
   REFERENCES USERS (USER_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT UQ_EMPLOYEE_USER UNIQUE (EMPLOYEE_ID, USER_ID);

ALTER TABLE AUDIT_HISTORIES
ADD CONSTRAINT AUDIT_HISTORY_USER_FK
   FOREIGN KEY (USER_ID)
   REFERENCES USERS (USER_ID);

ALTER TABLE AUDIT_HISTORIES
ADD CONSTRAINT AUDIT_HISTORY_OPERATION_FK
   FOREIGN KEY (AUDIT_OPERATION_ID)
   REFERENCES AUDIT_OPERATIONS (AUDIT_OPERATION_ID);

ALTER TABLE AUDIT_HISTORIES
ADD CONSTRAINT IS_ERROR_BOOLEAN_CHECK
   CHECK (IS_ERROR IN (0, 1));

ALTER TABLE USERS
ADD CONSTRAINT IS_ACTIVE_BOOLEAN_CHECK
   CHECK (IS_ACTIVE IN (0, 1));

ALTER TABLE USERS
ADD CONSTRAINT UQ_USER_LOGIN UNIQUE (LOGIN);

--INDEXES

CREATE INDEX EMPLOYEE_POSITION_IDX ON EMPLOYEES (POSITION_ID);
CREATE INDEX EMPLOYEE_DEPARTMENT_IDX ON EMPLOYEES (DEPARTMENT_ID);
CREATE INDEX EMPLOYEE_USER_IDX ON EMPLOYEES (USER_ID);
CREATE INDEX AUDIT_HISTORY_OPERATION_IDX ON AUDIT_HISTORIES (AUDIT_OPERATION_ID);
CREATE INDEX AUDIT_HISTORY_USER_IDX ON AUDIT_HISTORIES (USER_ID);
