CREATE TABLE STATISTICS
(STATISTIC_ID NUMBER (19, 0) NOT NULL,
  STATISTIC_MARK VARCHAR2 (255 CHAR) NOT NULL,
  PAGE_NAME VARCHAR2 (4000 CHAR) NOT NULL,
  IP_ADDRESS VARCHAR2 (255 CHAR) NOT NULL,
  BROWSER_INFO VARCHAR2 (255 CHAR) NOT NULL,
  VISIT_DATE DATE NOT NULL,
  COOKIES VARCHAR2 (4000 CHAR) NOT NULL,
  REQUESTED_PARAMS VARCHAR2 (4000 CHAR) NOT NULL,
  PREV_STATISTIC_ID NUMBER (19, 0),
  CONSTRAINT PK_STATISTIC_ID PRIMARY KEY (STATISTIC_ID));

CREATE SEQUENCE STATISTICS_SEQ START WITH 1;

--FOREIGN KEYS

ALTER TABLE STATISTICS
ADD CONSTRAINT PREV_STATISTIC_FK
   FOREIGN KEY (PREV_STATISTIC_ID)
   REFERENCES STATISTICS (STATISTIC_ID);

--INDEXES

CREATE INDEX PREV_STAT_ID_IDX ON STATISTICS (PREV_STATISTIC_ID);