
package ru.otus.akn.project.soap.taxes.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaxesCalculatorService", targetNamespace = "http://taxes.soap.project.akn.otus.ru/", wsdlLocation = "http://localhost:8080/TaxesCalculatorService?wsdl")
public class TaxesCalculatorService
    extends Service
{

    private final static URL TAXESCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException TAXESCALCULATORSERVICE_EXCEPTION;
    private final static QName TAXESCALCULATORSERVICE_QNAME = new QName("http://taxes.soap.project.akn.otus.ru/", "TaxesCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TaxesCalculatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAXESCALCULATORSERVICE_WSDL_LOCATION = url;
        TAXESCALCULATORSERVICE_EXCEPTION = e;
    }

    public TaxesCalculatorService() {
        super(__getWsdlLocation(), TAXESCALCULATORSERVICE_QNAME);
    }

    public TaxesCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAXESCALCULATORSERVICE_QNAME, features);
    }

    public TaxesCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, TAXESCALCULATORSERVICE_QNAME);
    }

    public TaxesCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAXESCALCULATORSERVICE_QNAME, features);
    }

    public TaxesCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxesCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaxesCalculatorProvider
     */
    @WebEndpoint(name = "TaxesCalculatorProviderPort")
    public TaxesCalculatorProvider getTaxesCalculatorProviderPort() {
        return super.getPort(new QName("http://taxes.soap.project.akn.otus.ru/", "TaxesCalculatorProviderPort"), TaxesCalculatorProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxesCalculatorProvider
     */
    @WebEndpoint(name = "TaxesCalculatorProviderPort")
    public TaxesCalculatorProvider getTaxesCalculatorProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://taxes.soap.project.akn.otus.ru/", "TaxesCalculatorProviderPort"), TaxesCalculatorProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAXESCALCULATORSERVICE_EXCEPTION!= null) {
            throw TAXESCALCULATORSERVICE_EXCEPTION;
        }
        return TAXESCALCULATORSERVICE_WSDL_LOCATION;
    }

}
