
package ru.otus.akn.project.soap.taxes.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigDecimal;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "TaxesCalculatorProvider", targetNamespace = "http://taxes.soap.project.akn.otus.ru/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TaxesCalculatorProvider {


    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateTaxes", targetNamespace = "http://taxes.soap.project.akn.otus.ru/", className = "ru.otus.akn.project.soap.taxes.client.CalculateTaxes")
    @ResponseWrapper(localName = "calculateTaxesResponse", targetNamespace = "http://taxes.soap.project.akn.otus.ru/", className = "ru.otus.akn.project.soap.taxes.client.CalculateTaxesResponse")
    @Action(input = "http://taxes.soap.project.akn.otus.ru/TaxesCalculatorProvider/calculateTaxesRequest", output = "http://taxes.soap.project.akn.otus.ru/TaxesCalculatorProvider/calculateTaxesResponse")
    public BigDecimal calculateTaxes(
            @WebParam(name = "arg0", targetNamespace = "")
                    BigDecimal arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    BigDecimal arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    BigDecimal arg2);

}
